"""
DNS Query Monitor — detects suspicious DNS activity.

Detections:
  - DNS tunneling     — unusually long/high-entropy subdomain    T1071.004
  - DGA domain        — algorithmically generated domain name     T1568.002
  - Suspicious TLD    — .tk/.ml/.ga abuse TLDs                   T1071.004
  - Excessive queries — same domain >20x in 60s                 T1071.004
  - Unusual resolver  — DNS query not to known resolvers          T1071.004

Platform support:
  Linux   — parses /var/log/syslog for dnsmasq/named/systemd-resolved
  Windows — Windows DNS-Client/Operational event log (EventID 3006/3008/3020)
  macOS   — unified log for mDNSResponder
"""
import math
import os
import re
import sys
import logging
import time
from collections import defaultdict
from datetime import datetime, timezone
from typing import Any, Dict, List

logger = logging.getLogger(__name__)

# ── Suspicious TLDs (top free-TLD abuse) ─────────────────────────────────────
_SUSPICIOUS_TLDS = frozenset({
    '.tk', '.ml', '.ga', '.cf', '.gq',
    '.xyz', '.top', '.work', '.click', '.loan',
    '.download', '.accountant', '.stream', '.faith',
    '.win', '.racing', '.party', '.science', '.date',
    '.review', '.bid', '.trade', '.webcam', '.link',
})

# ── Known benign domains (skip entropy checks) ───────────────────────────────
_WHITELIST = frozenset({
    'google.com', 'googleapis.com', 'gstatic.com', 'youtube.com',
    'facebook.com', 'fbcdn.net', 'amazon.com', 'amazonaws.com',
    'microsoft.com', 'windows.com', 'windowsupdate.com',
    'apple.com', 'icloud.com', 'akamaitechnologies.com',
    'cloudflare.com', 'fastly.net', 'akamaiedge.net',
})

# ── Detection thresholds ──────────────────────────────────────────────────────
_DGA_ENTROPY     = 3.8    # Shannon entropy threshold (bits/char)
_DGA_MIN_LEN     = 12     # minimum label length to check
_TUNNEL_LEN      = 45     # subdomain length for tunneling detection
_TUNNEL_B64_LEN  = 25     # label length for base64-pattern tunneling
_RATE_WINDOW     = 60     # seconds for rate tracking
_RATE_THRESHOLD  = 20     # queries to same domain in window

# ── State ─────────────────────────────────────────────────────────────────────
_query_rate: Dict[str, List[float]] = defaultdict(list)
_syslog_pos: int = 0
_win_dns_pos: int = 0


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _shannon_entropy(s: str) -> float:
    if not s:
        return 0.0
    freq: Dict[str, int] = {}
    for c in s:
        freq[c] = freq.get(c, 0) + 1
    n = len(s)
    return -sum((cnt / n) * math.log2(cnt / n) for cnt in freq.values())


def _extract_registered_domain(fqdn: str) -> str:
    """Return 'example.com' from 'sub.example.com'."""
    parts = fqdn.rstrip('.').split('.')
    if len(parts) >= 2:
        return '.'.join(parts[-2:])
    return fqdn


def _is_whitelisted(domain: str) -> bool:
    rd = _extract_registered_domain(domain)
    return rd in _WHITELIST


def _is_suspicious_tld(domain: str) -> bool:
    for tld in _SUSPICIOUS_TLDS:
        if domain.endswith(tld):
            return True
    return False


def _is_dga(domain: str) -> bool:
    """High-entropy label likely generated by DGA."""
    parts = domain.split('.')
    if len(parts) < 2:
        return False
    label = parts[0]
    if len(label) < _DGA_MIN_LEN:
        return False
    # Filter numeric-only (IP-like) labels
    if label.replace('-', '').isdigit():
        return False
    return _shannon_entropy(label) >= _DGA_ENTROPY


def _is_dns_tunnel(domain: str) -> bool:
    """Long or base64-like subdomain suggests DNS tunneling."""
    parts = domain.split('.')
    for part in parts[:-2]:   # skip TLD parts
        if len(part) >= _TUNNEL_LEN:
            return True
        if (len(part) >= _TUNNEL_B64_LEN
                and re.match(r'^[a-zA-Z0-9+/=_-]+$', part)
                and _shannon_entropy(part) > 3.5):
            return True
    return False


def _update_rate(domain: str) -> int:
    """Update query rate counter. Returns count in current window."""
    now = time.monotonic()
    times = _query_rate[domain]
    times.append(now)
    cutoff = now - _RATE_WINDOW
    while times and times[0] < cutoff:
        times.pop(0)
    # Evict stale domains to prevent memory growth
    if len(_query_rate) > 10_000:
        stale = [k for k, v in _query_rate.items() if not v or v[-1] < cutoff]
        for k in stale[:1000]:
            del _query_rate[k]
    return len(times)


def _make_alert(severity: str, event_type: str, domain: str,
                detail: str, mitre: str, extra: dict = None) -> Dict[str, Any]:
    msg = f"DNS [{event_type.upper()}]: {detail}"
    fields: Dict[str, Any] = {
        'event_type':      event_type,
        'domain':          domain,
        'detail':          detail,
        'mitre_technique': mitre,
    }
    if extra:
        fields.update(extra)
    return {
        'timestamp':     _now(),
        'level':         severity,
        'source':        'dns_monitor',
        'message':       msg,
        'raw':           msg,
        'parsed_fields': fields,
    }


def _analyze_domain(domain: str) -> List[Dict[str, Any]]:
    """Run all detection checks on a single domain. Returns 0 or more alerts."""
    domain = domain.lower().strip().rstrip('.')
    if not domain or len(domain) < 4 or '.' not in domain:
        return []
    if _is_whitelisted(domain):
        return []

    alerts = []

    # Rate check (always run)
    count = _update_rate(domain)
    if count > _RATE_THRESHOLD:
        alerts.append(_make_alert(
            'HIGH', 'dns_query_flood',
            domain,
            f"Domain {domain!r} queried {count}x in {_RATE_WINDOW}s — possible DDoS or C2 beacon",
            'T1071.004',
            {'query_count': count, 'window_sec': _RATE_WINDOW},
        ))
        return alerts   # don't stack with other alerts for same domain

    if _is_dns_tunnel(domain):
        alerts.append(_make_alert(
            'CRITICAL', 'dns_tunneling',
            domain,
            f"DNS tunneling detected: unusually long subdomain in {domain}",
            'T1071.004',
            {'subdomain_len': max(len(p) for p in domain.split('.')[:-2] or [''])},
        ))
    elif _is_dga(domain):
        entropy = round(_shannon_entropy(domain.split('.')[0]), 2)
        alerts.append(_make_alert(
            'HIGH', 'dga_domain',
            domain,
            f"DGA-style domain detected (entropy={entropy}): {domain}",
            'T1568.002',
            {'entropy': entropy, 'label': domain.split('.')[0]},
        ))
    elif _is_suspicious_tld(domain):
        alerts.append(_make_alert(
            'MEDIUM', 'suspicious_tld_query',
            domain,
            f"Query to abuse-prone TLD: {domain}",
            'T1071.004',
        ))

    return alerts


# ── Linux syslog parser ───────────────────────────────────────────────────────

_LINUX_DNS_RE = re.compile(
    r'(?:dnsmasq(?:\[\d+\])?|named\[\d+\]|systemd-resolved\[\d+\]|unbound\[\d+\])'
    r'.*?(?:query(?:\[(?:A|AAAA|MX|TXT|ANY)\])?|resolv(?:ed|ing)|forward)\s+'
    r'([a-zA-Z0-9._-]{4,})',
    re.IGNORECASE,
)


def _collect_linux() -> List[Dict[str, Any]]:
    global _syslog_pos
    alerts: List[Dict[str, Any]] = []

    for path in ('/var/log/syslog', '/var/log/messages'):
        if not os.path.exists(path):
            continue
        try:
            size = os.path.getsize(path)
            if size < _syslog_pos:
                _syslog_pos = 0  # log rotated

            with open(path, 'r', errors='replace') as f:
                f.seek(_syslog_pos)
                lines = 0
                for line in f:
                    if lines >= 3000:
                        break
                    lines += 1
                    m = _LINUX_DNS_RE.search(line)
                    if m:
                        alerts.extend(_analyze_domain(m.group(1)))
                _syslog_pos = f.tell()
        except (PermissionError, OSError):
            pass
        except Exception as e:
            logger.debug(f"DNS/Linux: {e}")
        break   # only need one file

    return alerts


# ── Windows DNS event log parser ─────────────────────────────────────────────

def _collect_windows() -> List[Dict[str, Any]]:
    global _win_dns_pos
    alerts: List[Dict[str, Any]] = []
    try:
        import win32evtlog
        import win32evtlogutil

        log_name = 'Microsoft-Windows-DNS-Client/Operational'
        hand = win32evtlog.OpenEventLog('localhost', log_name)
        total = win32evtlog.GetNumberOfEventLogRecords(hand)
        if total > _win_dns_pos:
            raw = win32evtlog.ReadEventLog(
                hand,
                win32evtlog.EVENTLOG_FORWARDS_READ | win32evtlog.EVENTLOG_SEEK_READ,
                _win_dns_pos,
            )
            for event in raw:
                if event.EventID in (3006, 3008, 3020, 3050, 3051):
                    try:
                        msg = win32evtlogutil.SafeFormatMessage(event, log_name) or ''
                        m = re.search(
                            r'(?:name|query|record)\s+([a-zA-Z0-9._-]{4,})', msg, re.I
                        )
                        if m:
                            alerts.extend(_analyze_domain(m.group(1)))
                    except Exception:
                        pass
            _win_dns_pos = total
        win32evtlog.CloseEventLog(hand)
    except Exception:
        pass
    return alerts


# ── macOS mDNSResponder parser ────────────────────────────────────────────────

def _collect_macos() -> List[Dict[str, Any]]:
    alerts: List[Dict[str, Any]] = []
    try:
        import subprocess
        result = subprocess.run(
            [
                'log', 'show',
                '--predicate', 'subsystem == "com.apple.mDNSResponder"',
                '--last', '60s',
                '--style', 'compact',
            ],
            capture_output=True, text=True, timeout=10,
        )
        for line in result.stdout.splitlines():
            m = re.search(
                r'(?:Question|AddRecord|QueryRec)\s+([a-zA-Z0-9._-]{4,})', line, re.I
            )
            if m:
                alerts.extend(_analyze_domain(m.group(1)))
    except Exception as e:
        logger.debug(f"DNS/macOS: {e}")
    return alerts


# ── Public API ────────────────────────────────────────────────────────────────

def collect_dns_events() -> List[Dict[str, Any]]:
    """Collect and analyze DNS events. Returns list of alert log dicts."""
    if sys.platform == 'win32':
        return _collect_windows()
    elif sys.platform == 'darwin':
        return _collect_macos()
    else:
        return _collect_linux()
